### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by MathMagique** [dirkjonker/sqlalchemy-turbodbc#1]
I just released turbodbc 1.1.0 to PyPI, so I think you should be able to release sqlalchemy-turbodbc to PyPI as well :-).

**Comment by dirkjonker** [comment]
Thanks! Will work on that soon

**Comment by dirkjonker** [comment]
Done! https://pypi.python.org/pypi/sqlalchemy-turbodbc

**Comment by MathMagique** [comment]
And advertised :-) https://twitter.com/turbodbc/status/848875007858094080
