### ISSUE TITLE
NoSuchModuleError after pip install of dialect

### ISSUE THREAD

**Issue by tomanizer** [dirkjonker/sqlalchemy-turbodbc#2]
Dialect might be installed into the wrong folder when using pip install.

Reproduce:

With a running turbodbc installation.
after
`pip install sqlalchemy-turbodbc `
run
`engine = create_engine(f'mssql+turbodbc://{connectionstring}')`
raises:
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.turbodbc

Also:
`import sqlalchemy.dialects.mssql.turbodbc`
fails

Checking the install shows that the turbodbc dialect.py  was installed in the folder
.\Lib\site-packages\sqlalchemy_turbodbc
when perhaps it should be installed here
.Lib\site-packages\sqlalchemy\dialects\mssql

**Comment by tomanizer** [comment]
Imports:

```
import turbodbc
import sqlalchemy_turbodbc
from sqlalchemy import create_engine
```

**Comment by dirkjonker** [comment]
Hi @tomanizer thanks for the bug report! It used to work fine, perhaps some things have changed with newer versions.
What version of Python, Turbodbc, and SQLAlchemy are you using?

**Comment by tomanizer** [comment]
Hi @dirkjonker. I tried again on a fresh install and it worked fine. It’s something with my environment. Will close the bug report. And thanks for the great work on this.
