### ISSUE TITLE
Unable to use odbc driver to create engine using sqlalchemy-turbodbc connector 

### ISSUE THREAD

**Issue by manishpunjabi21** [dirkjonker/sqlalchemy-turbodbc#3]
Using sqlalchemy and sql server I am able to connect by creating engine using the following command 

create_engine("mssql+pyodbc:///?odbc_connect=driver={ODBC Driver 13 for SQL Server}; server={servername};database={dbname}; trusted_connection=yes") 

However, when I change it to turbodc 
create_engine("mssql+turbodbc:///?odbc_connect=driver={ODBC Driver 13 for SQL Server}; server={servername};database={dbname}; trusted_connection=yes") 

I get the following exception 

sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.turbodbc

**Comment by dirkjonker** [comment]
Thanks for reporting this issue! What version of SQLAlchemy and Turbodbc are you using?

**Comment by dirkjonker** [comment]
@manishpunjabi21 without the ability to reproduce the error I cannot help you unfortunately. I am closing this issue. If you can provide me with enough information to reproduce the issue I will happily reopen and investigate for you.
