### ISSUE TITLE
DatabaseError: (turbodbc.exceptions.DatabaseError) when writing df to SQL

### ISSUE THREAD

**Issue by CorinneKnoe** [dirkjonker/sqlalchemy-turbodbc#5]
I import the packages 

`import turbodbc`
`import sqlalchemy_turbodbc`
`from sqlalchemy import create_engine`

I create the connection and engine:
`cnxn = turbodbc.connect("connection_string")  `  
`cnx = create_engine('mssql+turbodbc://{"connection_string"})`
But when I try to run 
`df.to_sql(name = folderstructure, con=cnx, if_exists = 'append', index=False) `

I get the following error message:

`DatabaseError: (turbodbc.exceptions.DatabaseError) ODBC error
state: IM002`
`native error code: 0`
`message: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified`
`(Background on this error at: http://sqlalche.me/e/4xp6)`

It works with pyodbc but is prohibitively slow. Any ideas what the issue could be? I have sqlalchemy-turbodbc 0.1.0. installd. Many thanks.

**Comment by dirkjonker** [comment]
Thanks for opening a ticket! There seems to be an issue with your ODBC settings. This error is related to the database itself, not SQLAlchemy or Turbodbc or the sqlalchemy-turbodbc package.

But no worries, I'm willing to help you out here. Are you using Windows? Can you post the entire connection string (you can change the database name and username/password with `xxxx` or something)?

**Comment by CorinneKnoe** [comment]
That is super nice of you. So, I am using Windows 10, and the code is

`cnxn = turbodbc.connect(connection_string="Driver={SQL Server Native Client 11.0};Server={myServer};Database={myDatabase};Trusted_Connection=yes;")`

and the engine 

`cnx = create_engine('mssql+turbodbc://@{myServer}/{myDatabase}')`
 
The thing is, that I can do:

`cursor = cnxn.cursor()`
`cursor.execute({SQLStatementToCreateTable})`
`cnxn.commit()`

The table is created. Likewise, I can insert values with `cursor.executemanycolumns({InsertRowCommand})`

That's why I thought that it's just the `df.to_sql()` command that's acting up because I messed up with sqlalchemy-turbodbc somehow.

**Comment by dirkjonker** [comment]
Strange, maybe you are using the wrong driver? Can you try with the ODBC driver version 13 and use `Driver={ODBC Driver 13 for SQL Server}` ?

**Comment by CorinneKnoe** [comment]
Unfortunately, that doesn't help. I changed the connect line to:
`cnxn = turbodbc.connect(connection_string="Driver={ODBC Driver 13 for SQL Server};Server={myServer};Database={myDatabase};Trusted_Connection=yes;")`

Like before, I can create a table if I pass an SQL command to the cursor. If I try
`df.to_sql(name = folderstructure, con=cnx, if_exists = 'append', index=False) `

I get the same error message as above.

I think the engine mus not be created correctly, as everything linked to the connection `cnxn` seems to work. 
I import  
`import turbodbc`
`import sqlalchemy_turbodbc`
`from sqlalchemy import create_engine`

and create the engine:
`cnx = create_engine('mssql+turbodbc://@{myServer}/{myDatabase}')`

Any obvous mistakes here?

**Comment by dirkjonker** [comment]
Can you try [creating a user or system DSN](https://docs.microsoft.com/en-us/sql/integration-services/import-export-data/connect-to-an-odbc-data-source-sql-server-import-and-export-wizard?view=sql-server-2017#odbc_dsn) and connect using that?
E.g. if the name of your DSN is `mydsn` then the connection becomes `create_engine('mssql+turbodbc://mydsn')`

I remember having some connection string issues in the past, but unfortunately I do not have a Windows environment nearby to see if I can reproduce your error.

**Comment by dirkjonker** [comment]
Obviously it has been some time since I last used this. Please also make sure you check out this section of the SQLAlchemy documentation on using pyodbc, basically the same information holds as this package is mostly copied code from the pyodbc adapter.
 https://docs.sqlalchemy.org/en/13/dialects/mssql.html#connecting-to-pyodbc

**Comment by dirkjonker** [comment]
Hi @CorinneKnoe please let me know if any of this helps. I just tried connecting with DSN and it seems to work for me. I will see if I anything could use an update (e.g. decimal support) and release a new version if so.

**Comment by CorinneKnoe** [comment]
Hi @dirkjonker, I am still working on it. In fact, I produced the same error with another package, so as you said, it's my connection not your package. However, I've not been able yet to create a DSN. I'm still looking into it.

**Comment by CorinneKnoe** [comment]
Hi @dirkjonker, thanks for your patience and help. The error is the following: when using a dsn-less connection, the driver needs to be specified in the `create_engine()` statement. So, the correct code is:
`cnx = create_engine('mssql+turbodbc://@myServer/myDatabase?driver=ODBC+Driver+13+for+SQL+Server')` 
More info on the issue here: https://stackoverflow.com/questions/37161574/using-pyodbc-cause-error-data-source-name-not-found-and-no-default-driver-speci 

This is on me. You explicitely stated that "[it] should work exactly like the `mssql+pyodbc` dialect as described in the SQLAlchemy documentation". I just didn't realize that this was the correct syntax for `pyodbc` as well. 

Thanks and cheers!

**Comment by dirkjonker** [comment]
Thanks @CorinneKnoe for coming back with the solution. I will update the README so hopefully it helps others in the future as well.
