### ISSUE TITLE
Issue installing mssql turbodbc

### ISSUE THREAD

**Issue by lgonzalezsa** [dirkjonker/sqlalchemy-turbodbc#7]
Hello All,

Was trying installing the module but not sure what I missing in my env, here the output:
`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -Iinclude/ -I/usr/include/python3.6m -I/usr/include/python3.6m -c src/cpp_odbc/statement.cpp -o build/temp.linux-x86_64-3.6/src/cpp_odbc/statement.o --std=c++11
    In file included from include/cpp_odbc/statement.h:4:0,
                     from src/cpp_odbc/statement.cpp:1:
    include/cpp_odbc/column_description.h:6:10: fatal error: sqltypes.h: No such file or directory
     #include "sqltypes.h"
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4_l7irra/turbodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-acdplnw7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4_l7irra/turbodbc/
`

Any help appreciated!

**Comment by dirkjonker** [comment]
The answer is in the error: `fatal error: sqltypes.h: No such file or directory`
You are missing the `sqltypes.h` header file, which probably means you are missing unixODBC. If you are using Linux or macOS you need to install the unixODBC development package for your operating system (e.g. `unixODBC-devel` or `unixodbc-dev` or something similar).

Please carefully read the Turbodbc documentation to see what requirements are needed for your system: https://turbodbc.readthedocs.io/en/latest/pages/getting_started.html

If you are still having issues with compiling Turbodbc after following the documentation, please open an issue in the repository for Turbodbc: https://github.com/blue-yonder/turbodbc/
