### ISSUE TITLE
sqlalchemy.exc.DatabaseError: (turbodbc.exceptions.DatabaseError) ODBC error state: IM002 native error code: 0 message: [unixODBC][Driver Manager]Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by sean-ashley** [dirkjonker/sqlalchemy-turbodbc#8]
Hello, I am having trouble getting turbobdc is running. I have everything installed, and the connection string runs when I am using pyodbc.

My code is as follows.

```
from sqlalchemy import create_engine
import urllib
from flask_sqlalchemy import SQLAlchemy
import time
import turbodbc
import sqlalchemy_turbodbc


driver = "ODBC Driver 17 for SQL Server"

params = urllib.parse.quote_plus \
(f'Driver={driver};'
 f'Server=xxxx'
 f'Database={database};'
 f'Uid=xxxx'
 f'Pwd=xxxx'
 f'Encrypt=yes;'
 f'TrustServerCertificate=no;'
 f'Connection Timeout=30')

conn_str = 'mssql+turbodbc:///?odbc_connect={}'.format(params)


                        

engine = create_engine(conn_str)

```
Once again, it all works for pyodbc , so I am not sure what the problem is.
Any help would be much appreciated.

Regards,
Sean.

**Comment by sean-ashley** [comment]
note I am on ubuntu 20.10

**Comment by dirkjonker** [comment]
Are you able to connect to your data source using Turbodbc directly? i.e. without SQLAlchemy?

**Comment by dirkjonker** [comment]
If you can, try setting up the connection through unixODBC, see https://turbodbc.readthedocs.io/en/latest/pages/databases/mssql.html for instructions.

It seems Turbodbc may not be compatible with the "PyODBC connection string" method that you are using. I will alter the README to reflect that.

**Comment by sean-ashley** [comment]
@dirkjonker  I will try connecting directly right now, and I will try altering the PyODBC connection string. I will let you know if those work, thanks for the help!

**Comment by sean-ashley** [comment]
> Are you able to connect to your data source using Turbodbc directly? i.e. without SQLAlchemy?

@dirkjonker , I was able to connect directly using this connection = connect(connection_string='Driver={ODBC Driver 17 for SQL Server};Server=xxxx;Database=xxxx;Uid=xxxx;Pwd=xxxx;')
I am not sure why, but I still not to be able to use it with SQLAlchemy to get it working with the system I am working with.

**Comment by gordthompson** [comment]
Support for `?odbc_connect=…` is implemented in SQLAlchemy at the (pyodbc) "connector" level as opposed to the "driver" level:

https://github.com/sqlalchemy/sqlalchemy/blob/10c1b1846dd0c205fe5af80daeb0145c9cbd75c8/lib/sqlalchemy/connectors/pyodbc.py#L55

Third-party dialects using ODBC DBAPIs other than pyodbc will need to replicate that logic themselves if they want to support the ["Pass through exact Pyodbc string"](https://docs.sqlalchemy.org/en/14/dialects/mssql.html#pass-through-exact-pyodbc-string) connection method.

**Comment by dirkjonker** [comment]
Thanks @gordthompson for the clarification.

@sean-ashley have you tried setting up a connection using an ODBC DSN? As described here: https://turbodbc.readthedocs.io/en/latest/pages/databases/mssql.html

Then you should be able to use something similar to what's in the README, assuming your DSN is named "mydsn":

```python
create_engine('mssql+turbodbc://scott:tiger@mydsn')
```

Or, if for whatever reason you cannot configure ODBC, you may try the traditional SQLalchemy connection string, as described here: https://docs.sqlalchemy.org/en/13/dialects/mssql.html#hostname-connections

```python
create_engine("mssql+turbodbc://scott:tiger@myhost:port/databasename?driver=SQL+Server+Native+Client+10.0")
```

**Comment by gordthompson** [comment]
> Or, if for whatever reason you cannot configure ODBC

Installing "ODBC Driver 17 for SQL Server" according to the directions [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15) will create the appropriate entry in "/etc/odbcinst.ini" (at least for Ubuntu). It is able to do that because sudo permissions are required to install the driver.

Once the driver is installed, a user without sudo privileges can still create their own ODBC "User DSN" definition by putting it into "~/.odbc.ini".

**Comment by sean-ashley** [comment]
> Thanks @gordthompson for the clarification.
> 
> @sean-ashley have you tried setting up a connection using an ODBC DSN? As described here: https://turbodbc.readthedocs.io/en/latest/pages/databases/mssql.html
> 
> Then you should be able to use something similar to what's in the README, assuming your DSN is named "mydsn":
> 
> ```python
> create_engine('mssql+turbodbc://scott:tiger@mydsn')
> ```
> 
> Or, if for whatever reason you cannot configure ODBC, you may try the traditional SQLalchemy connection string, as described here: https://docs.sqlalchemy.org/en/13/dialects/mssql.html#hostname-connections
> 
> ```python
> create_engine("mssql+turbodbc://scott:tiger@myhost:port/databasename?driver=SQL+Server+Native+Client+10.0")
> ```

I will give that a shot and get back to you!

**Comment by dirkjonker** [comment]
@gordthompson thanks for the additional information. In some cases (i.e.

**Comment by dirkjonker** [comment]
Sorry, accidentally closed this by clicking on the wrong button. @gordthompson thanks for the additional information!

**Comment by sean-ashley** [comment]
I managed to solve the issue by using this connection string 
conn_str = "mssql+turbodbc://{username}:{password}@{host}:{port}/{database}?driver={driver}".format(
    username = username ,password=password, 
    host=host, port=port, database=database, driver = driver), thanks for the help!!
